"""
Sample data insertion script

Inserts sample product data into Milvus.
"""

import argparse
import os
import sys
from pathlib import Path
from pymilvus import MilvusClient

from common import (
    IS_JA,
    PARTICIPANT_LANGUAGE,
    connect_to_milvus,
    get_entity_count,
    load_embedding_model,
    msg,
)
from sample_products import get_sample_products
from schema import (
    VECTOR_FIELD,
    build_collection_schema,
    build_index_params,
    get_collection_name,
    product_text,
)


SAMPLE_PRODUCTS = get_sample_products(PARTICIPANT_LANGUAGE)
COLLECTION_NAME = get_collection_name()


def parse_args():
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description=msg("Insert sample product data into Milvus", "Milvus にサンプル商品データを挿入します")
    )
    parser.add_argument(
        "-y", "--yes",
        action="store_true",
        help=msg(
            "Drop an existing collection without asking for confirmation",
            "既存コレクションを確認なしで削除する"
        )
    )
    return parser.parse_args()


def print_start_commands():
    """Show commands that work from the current directory."""
    participant_dir = Path(__file__).resolve().parent
    current_dir = Path.cwd().resolve()
    venv_python = "venv\\Scripts\\python" if os.name == "nt" else "venv/bin/python"
    participant_cd = "setup\\participant" if os.name == "nt" else "setup/participant"
    python_command = f"{venv_python} app.py" if (participant_dir / "venv").exists() else "python app.py"

    if current_dir == participant_dir:
        print(f"  {python_command}")
    else:
        print(f"  cd {participant_cd}")
        print(f"  {python_command}")


def confirm_drop(client: MilvusClient, assume_yes: bool) -> bool:
    """Ask before dropping an existing collection (it may be shared with others)."""
    entity_count = get_entity_count(client, COLLECTION_NAME)
    print(f"\n⚠ {msg('Collection already exists', 'コレクションは既に存在します')}: "
          f"{COLLECTION_NAME} ({entity_count} {msg('entities', '件')})")
    print(msg(
        "  On a shared Milvus, dropping a collection also deletes other participants' data.",
        "  共有 Milvus では、コレクションを削除すると他の参加者のデータも消えます。"
    ))

    if assume_yes:
        return True

    prompt = msg("Drop and recreate this collection? [y/N]: ",
                 "このコレクションを削除して作り直しますか？ [y/N]: ")
    try:
        answer = input(prompt).strip().lower()
    except EOFError:
        answer = ""
    return answer in ("y", "yes")


def drop_existing_collection(client: MilvusClient, assume_yes: bool) -> bool:
    """Drop existing collection after confirmation. Return False when aborted."""
    if not client.has_collection(COLLECTION_NAME):
        return True

    if not confirm_drop(client, assume_yes):
        print(f"\n{msg('Aborted. No data was changed.', '中止しました。データは変更されていません。')}")
        print(msg(
            "  To use your own collection, set a unique COLLECTION_NAME in setup/participant/.env "
            "(e.g. products_taro).",
            "  自分専用のコレクションを使うには、setup/participant/.env の COLLECTION_NAME を"
            "一意な名前（例: products_taro）に変更してください。"
        ))
        return False

    print(f"\n{msg('Dropping existing collection', '既存のコレクションを削除中')}: {COLLECTION_NAME}")
    client.drop_collection(COLLECTION_NAME)
    print(f"✓ {msg('Collection dropped', 'コレクションを削除しました')}: {COLLECTION_NAME}")
    return True


def create_collection(client: MilvusClient, embedding_dimension):
    """Create collection"""
    print(f"\n{msg('Creating collection', 'コレクションを作成中')}: {COLLECTION_NAME}")

    # Without index_params the collection is created but not loaded yet;
    # the index is built and the collection loaded after the insert
    client.create_collection(
        collection_name=COLLECTION_NAME,
        schema=build_collection_schema(embedding_dimension)
    )

    print(f"✓ {msg('Collection created', 'コレクションを作成しました')}: {COLLECTION_NAME}")


def create_index(client: MilvusClient):
    """Create index"""
    print(f"\n{msg('Creating index...', 'インデックスを作成中...')}")

    client.create_index(collection_name=COLLECTION_NAME, index_params=build_index_params())
    print(msg("✓ Index created", "✓ インデックスを作成しました"))


def insert_data(client: MilvusClient, embedding_model):
    """Insert data"""
    item_unit = "件" if IS_JA else "items"
    print(f"\n{msg('Inserting sample data...', 'サンプルデータを挿入中...')} ({len(SAMPLE_PRODUCTS)} {item_unit})")

    # Combine product name and description into text
    texts = [
        product_text(p)
        for p in SAMPLE_PRODUCTS
    ]

    # Convert text to vectors
    print(msg("  Generating embedding vectors...", "  埋め込みベクトルを生成中..."))
    embeddings = embedding_model.encode(texts, normalize_embeddings=True)

    # Prepare data: one row per product (the id is generated by Milvus)
    rows = [
        {
            "product_name": p["product_name"],
            "price": p["price"],
            "category": p["category"],
            "description": p["description"],
            VECTOR_FIELD: vector,
        }
        for p, vector in zip(SAMPLE_PRODUCTS, embeddings.tolist())
    ]

    # Insert data
    client.insert(collection_name=COLLECTION_NAME, data=rows)
    client.flush(collection_name=COLLECTION_NAME)

    print(f"✓ {len(SAMPLE_PRODUCTS)} {msg('items inserted', '件のデータを挿入しました')}")


def insert_sample_data(client: MilvusClient, assume_yes: bool) -> int:
    """Load the model, recreate the collection, and insert the sample products."""
    try:
        embedding_model = load_embedding_model()
    except Exception as e:
        print(f"✗ {msg('Failed to load embedding model', '埋め込みモデルの読み込みに失敗しました')}: {e}")
        return 1

    if not drop_existing_collection(client, assume_yes):
        return 1

    # Create collection (vector dimension comes from the loaded model)
    create_collection(client, embedding_model.get_embedding_dimension())

    # Insert data
    insert_data(client, embedding_model)

    # Create index
    create_index(client)

    # Load collection
    print(f"\n{msg('Loading collection...', 'コレクションを読み込み中...')}")
    client.load_collection(collection_name=COLLECTION_NAME)
    print(msg("✓ Collection loaded", "✓ コレクションを読み込みました"))

    # Display results
    print("\n" + "=" * 50)
    print(msg("✓ Sample data insertion completed", "✓ サンプルデータの挿入が完了しました"))
    print("=" * 50)
    print(f"\n{msg('Collection name', 'コレクション名')}: {COLLECTION_NAME}")
    print(f"{msg('Entity count', 'エンティティ数')}: {get_entity_count(client, COLLECTION_NAME)}")
    print(f"\n{msg('You can start the demo application', 'デモアプリケーションを起動できます')}:")
    print_start_commands()
    print("=" * 50 + "\n")
    return 0


def main() -> int:
    """Main process"""
    args = parse_args()

    print("=" * 50)
    print(msg("Sample Data Insertion Script", "サンプルデータ挿入スクリプト"))
    print("=" * 50)

    try:
        client = connect_to_milvus()
    except Exception as e:
        print(f"✗ {msg('Failed to connect to Milvus', 'Milvus への接続に失敗しました')}: {e}")
        return 1

    try:
        return insert_sample_data(client, args.yes)
    finally:
        client.close()


if __name__ == "__main__":
    sys.exit(main())
